## Задание №1. Создание и изменение массивов.

Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив. 

In [166]:
import numpy as np
mas = np.arange(1, 10).reshape(3, 3)

mas *= 2

mas[mas > 10] = 0

print("Итоговый массив:\n", mas)

Итоговый массив:
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## Задание №2. Работа с булевыми масками.

Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [169]:
mas = np.random.randint(1, 101, size=20)

mask = mas % 5 == 0
div5 = mas[mask]

mas[mask] = -1

print("Элементы, которые делятся на 5 без остатка:", div5, "\n")
print(mas)

Элементы, которые делятся на 5 без остатка: [85 25 45 80] 

[59 66 84 54 81  9 83  8 88 61 27 -1 53 88 -1 14 51 -1 -1 91]


## Задание №3. Объединение и разбиение массивов.

Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.

1. Объедините эти массивы в один двумерный массив (по строкам).
2. Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты.


In [172]:
mas1 = np.random.randint(0, 51, (1, 5))
mas2 = np.random.randint(0, 51, (1, 5))

print("Исходные массивы:\n", "1.", mas1, "\n", "2.", mas2, "\n")

combined_mas = np.vstack((mas1, mas2))

print("Объединённый массив:\n", combined_mas, "\n")

split_mas1, split_mas2 = np.split(combined_mas, 2)

print("Разделенный массив 1:", split_mas1)
print("Разделенный массив 2:", split_mas2)

Исходные массивы:
 1. [[24 44 29 32 40]] 
 2. [[ 8 44 28 12 43]] 

Объединённый массив:
 [[24 44 29 32 40]
 [ 8 44 28 12 43]] 

Разделенный массив 1: [[24 44 29 32 40]]
Разделенный массив 2: [[ 8 44 28 12 43]]


## Задание №4. Генерация и работа с линейными последовательностями.

Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [175]:
mas = np.random.uniform(-10, 10, 50)

sum_elements = np.sum(mas)

sum_positive = np.sum(mas[mas > 0])

sum_negative = np.sum(mas[mas < 0])

print("Массив:", mas)
print("Сумма всех элементов:", sum_elements)
print("Сумма положительных элементов:", sum_positive)
print("Сумма отрицательных элементов:", sum_negative)

Массив: [-7.32580646 -5.35414983 -1.28971222 -2.51347929  2.34504533  2.17733071
 -8.64389985 -6.80336461  7.78484921  9.60224375 -3.24720069  7.8878476
 -7.01550034 -8.71622496 -3.53358841 -7.88893166 -3.50311407 -5.30954396
 -5.66368184  5.70127339  3.692938    4.01453673  0.62262233  7.73817657
  5.00355164  5.84058029 -5.74619751 -1.29014904  4.49438474 -8.34861279
 -9.91725415 -4.52543035  4.75203691 -7.0390215   5.7217598   5.93414562
 -0.99144376  5.03373145 -8.89529661  7.97390646 -2.52218257  4.45756105
  9.29832127  3.26584639 -8.76181391 -9.53931396 -1.79386337 -0.13356523
  0.02284037  4.81644421]
Сумма всех элементов: -28.13036911694777
Сумма положительных элементов: 118.18197382127559
Сумма отрицательных элементов: -146.3123429382234


## Задание №5. Работа  с диагональными и единичными матрицами.

Создайте:

1. Единичную матрицу размером 4×4. 
2. Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.


In [178]:
matrix_eye = np.eye(4)
sum_matrix_eye = np.sum(matrix_eye)

matrix_eyeDiag = np.diag([5, 10, 15, 20])
sum_matrix_eyeDiag = np.sum(matrix_eyeDiag)

print("Единичная матрица:\n", matrix_eye)
print("Сумма элементов единичной матрицы:", sum_matrix_eye)

print("Диагональная матрица:\n", matrix_eyeDiag)
print("Сумма элементов диагональной матрицы:", sum_matrix_eyeDiag)

Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Сумма элементов единичной матрицы: 4.0
Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов диагональной матрицы: 50


## Задание №6. Создание и базовые операции с матрицами.

Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. 

Вычислите и выведите:
1. Их сумму
2. Их разность 
3. Их поэлементное произведение



In [181]:
matrix1 = np.matrix(np.random.randint(1, 21, (3, 3)))
matrix2 = np.matrix(np.random.randint(1, 21, (3, 3)))

sum_matrix = matrix1 + matrix2
diff_matrix = matrix1 - matrix2
el_product_matrix = np.multiply(matrix1, matrix2) 

print("Матрица №1:\n", matrix1)
print("Матрица №2:\n", matrix2)
print("Сумма матриц:\n", sum_matrix)
print("Разность матриц:\n", diff_matrix)
print("Поэлементное произведение матриц:\n", el_product_matrix)

Матрица №1:
 [[ 4  5 17]
 [12  4 19]
 [16 13 18]]
Матрица №2:
 [[18  2 19]
 [10  3  9]
 [18 12  7]]
Сумма матриц:
 [[22  7 36]
 [22  7 28]
 [34 25 25]]
Разность матриц:
 [[-14   3  -2]
 [  2   1  10]
 [ -2   1  11]]
Поэлементное произведение матриц:
 [[ 72  10 323]
 [120  12 171]
 [288 156 126]]


## Задание №7. Умножение матриц.

Создайте две матрицы NumPy: 

1. Первую размером 2×3, заполненную случайными числами от 1 до 10. 
2. Вторую размером 3×2, заполненную случайными числами от 1 до 10.

Выполните матричное умножение (@ или np.dot) и выведите результат


In [61]:
matrix1 = np.matrix(np.random.randint(1, 11, (2, 3)))
matrix2 = np.matrix(np.random.randint(1, 11, (3, 2)))

dot_matrix = np.dot(matrix1, matrix2)

print("Первая матрица:\n", matrix1)
print("Вторая матрица:\n", matrix2)
print("Результат матричного умножения:\n", dot_matrix)

Первая матрица:
 [[5 4 1]
 [6 9 7]]
Вторая матрица:
 [[ 2  2]
 [10  2]
 [ 7  5]]
Результат матричного умножения:
 [[ 57  23]
 [151  65]]


## Задание №8. Определитель и обратная матрица.

Создайте случайную квадратную матрицу 3×3. Найдите и выведите: 

1. Определитель этой матрицы 
2. Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена)
   
Используйте функции np.linalg.det и np.linalg.inv.


In [67]:
matrix = np.matrix(np.random.randint(1, 11, (3, 3)))
determinant = np.linalg.det(matrix)

if np.isclose(determinant, 0):
    print("Матрица вырожденная")
else:
    print("Обратная матрица:\n", np.linalg.inv(matrix))

Обратная матрица:
 [[ 22.  -19.    4.5]
 [ -6.    5.   -1. ]
 [ -9.    8.   -2. ]]


## Задание №9. Транспонирование и след матрицы.

Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите: 
1. Исходную матрицу 
2. Транспонированную матрицу 
3. След матрицы (сумму элементов на главной диагонали)
   
Используйте np.trace для нахождения следа.


In [69]:
matrix = np.matrix(np.random.randint(1, 51, (4, 4)))

transpons_matrix = matrix.T
trace_of_matrix = np.trace(matrix)

print("Исходная матрица:\n", matrix)
print("Транспонированная матрица:\n", transpons_matrix)
print("След матрицы:", trace_of_matrix)

Исходная матрица:
 [[ 3 16  5 21]
 [25  5  3 20]
 [21 12 48 11]
 [ 6 25 25 21]]
Транспонированная матрица:
 [[ 3 25 21  6]
 [16  5 12 25]
 [ 5  3 48 25]
 [21 20 11 21]]
След матрицы: 77


## Задание №10. Системы линейных уравнений.

Решить систему линейных уравнений.

\begin{cases}
2x + 3y - z = 5 \\
4x - y + 2z = 6 \\
-3x + 5y + 4z = -2
\end{cases}

Используйте матричное представление AX = B , где A – матрица коэффициентов,
x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
np.linalg.solve и выведите результат.

In [74]:
A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]])
B = np.array([5, 6, -2])
x = np.linalg.solve(A, B)

print("Решение системы уравнений:\n", x)

Решение системы уравнений:
 [1.63963964 0.57657658 0.00900901]


## Задание №11. 
Каждое задание предусматривает построение системы линейных уравнений. Решите полученную
систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.

**Вариант №13.** Три сотрудника должны выполнить работу за минимальное время. Первый выполняет задачу за 5 часов, второй — за 3 часа, а третий — за 2 часа. Как распределить работу между ними, если всего 20 задач?

Пусть:

1. $x_1$ - количество задач, выполненных первым сотрудником.
2. $x_2$ - количество задач, выполненных вторым сотрудником.
3. $x_3$ - количество задач, выполненных третим сотрудником.

Тогда: $x_1 + x_2 + x_3 = 20$

Учитывая скорость работы в час: $\frac{x_1}{5}$ = $\frac{x_2}{3}$ = $\frac{x_3}{2}$ = t

Получаем следующую систему уравнений:

\begin{cases} 
x_1 + x_2 + x_3 = 20 \\
3x_1 - 5x_2 = 0 \\ 
2x_1 - 5x_3 = 0 
\end{cases}


In [138]:
# Метод крамера

A = np.array([[1, 1, 1],
              [3, -5, 0],
              [2, 0, -5]])

B = np.array([20, 0, 0])

det_A = np.linalg.det(A)

A1 = A.copy()
A1[:, 0] = B
det_A1 = np.linalg.det(A1)

A2 = A.copy()
A2[:, 1] = B
det_A2 = np.linalg.det(A2)

A3 = A.copy()
A3[:, 2] = B
det_A3 = np.linalg.det(A3)

x1_cramer = round(det_A1 / det_A)
x2_cramer = round(det_A2 / det_A)
x3_cramer = round(det_A3 / det_A)

print("X1 =", x1_cramer, "\nX2 =", x2_cramer, "\nX3 =", x3_cramer)


X1 = 10 
X2 = 6 
X3 = 4


In [155]:
# Матричный метод

inverse_A = np.linalg.inv(A)
solution_matrix = inverse_A @ B

print("X1 =", round(solution_matrix[0]), "\nX2 =", round(solution_matrix[1]), "\nX3 =", round(solution_matrix[2]))

X1 = 10 
X2 = 6 
X3 = 4


In [161]:
# Решение с помощью np.linalg.solve

solution = np.linalg.solve(A, B)

print("X1 =", round(solution[0]), "\nX2 =", round(solution[1]), "\nX3 =", round(solution[2]))

X1 = 10 
X2 = 6 
X3 = 4


**Ответ:** Первый сотрудник выполняет 10 задач, второй — 6, третий — 4.